# Generated by Django 3.2.18 on 2023-04-06 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('members', '0006_hello'),
        ('precios_integration', '0002_planpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoPlanPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='precios_integration_contenidoplanpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('ContenidoPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.contenidoplan')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
