# Generated by Django 3.2.18 on 2023-05-24 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_initial'),
        ('cms', '0022_auto_20180620_1551'),
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='precios_integration_settingspluginmodel', serialize=False, to='cms.cmsplugin')),
                ('Settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precios.settings')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='PlanPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='precios_integration_planpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.plan')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContenidoPlanPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='precios_integration_contenidoplanpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('ContenidoPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.contenidoplan')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
