# Generated by Django 3.2.18 on 2023-05-24 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import meta.models
import precios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=50)),
                ('monto_minimo_compra', models.IntegerField(default=0, help_text='Monto desde el cual se cobra el siguiente valor del despacho', null=True)),
                ('valor_despacho', models.IntegerField(default=0, help_text='Costo del despacho', null=True)),
                ('dias_para_despacho', models.IntegerField(default=0, help_text='Dias que demora despacho', null=True)),
                ('dias_habiles', models.BooleanField(default=True, help_text='Dias Habiles = True')),
                ('datos_confiables', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Area de despacho',
                'verbose_name_plural': 'Areas de despacho',
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(default='', max_length=350)),
                ('nombre', models.CharField(max_length=350)),
                ('medida_um', models.CharField(default='', max_length=20)),
                ('medida_cant', models.FloatField(default=0)),
                ('unidades', models.IntegerField(default=0)),
                ('dimension', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('envase', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('grados', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('grados2', models.FloatField(default=0)),
                ('ean_13', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['marca__slug', 'nombre', 'medida_cant', 'unidades', 'grados2'], unique=True)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ('marca', 'nombre', 'medida_cant', 'grados', 'unidades'),
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='Campos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('donde', models.CharField(choices=[('En listado', 'En Listado'), ('En producto', 'En Producto'), ('Detalle en listado', 'Detalle En Listado')], default='En listado', help_text='Este campo es utilizado en ?', max_length=20)),
                ('campoQueGraba', models.CharField(default='', max_length=20)),
                ('es_multiple', models.BooleanField(default=True)),
                ('es_click', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('guardar_historico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='CamposEnSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evita', models.CharField(blank=True, help_text='Que clase evita en listados', max_length=650, null=True)),
                ('printit', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, default='', null=True)),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('campo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.campos')),
                ('hijoDe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='precios.camposensitio')),
            ],
            options={
                'verbose_name': 'Campo en sitio',
                'verbose_name_plural': 'Campos en sitio',
                'ordering': ('site', 'campo', 'my_order'),
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('notas', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Corporarcion',
                'verbose_name_plural': 'Corporarciones',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dia de la semana',
                'verbose_name_plural': 'Dias de la semana',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='precios_hello', serialize=False, to='cms.cmsplugin')),
                ('guest_name', models.CharField(default='Guest', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HorasDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField()),
                ('termino', models.TimeField()),
            ],
            options={
                'verbose_name': 'Hora de despacho',
                'verbose_name_plural': 'Horas de despacho',
                'ordering': ('inicio', 'termino'),
                'unique_together': {('inicio', 'termino')},
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='nombre', unique=True)),
                ('unificado', models.BooleanField(default=False)),
                ('es_marca', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='MarcasSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Marca sistema',
                'verbose_name_plural': 'Marcas sistema',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Key')),
                ('value', models.CharField(max_length=80, verbose_name='Value')),
                ('valor_data', models.TextField(default='')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(help_text='Nombre del sitio', max_length=250)),
                ('siteURL', models.CharField(help_text='URL del sitio', max_length=250)),
                ('agregaSiteURL', models.BooleanField(default=True, help_text='Agrega SiteURL a las URL de cada producto.')),
                ('allLinksInOnePage', models.BooleanField(default=True, help_text='Todos los productos en una pagina. No tiene Next Page.')),
                ('siteSearchEnabled', models.BooleanField(default=True)),
                ('siteSearch', models.CharField(choices=[('none', 'None'), ('crawler', 'Crawler'), ('sitemap', 'Sitemap')], default='none', help_text='Obtiene URL de productos usando...', max_length=20)),
                ('productSearchEnabled', models.BooleanField(default=True)),
                ('last_scan', models.DateTimeField(auto_now=True)),
                ('listHasClick', models.BooleanField(default=True)),
                ('listNeedsPgDn', models.BooleanField(default=False, help_text='El listado de prroductos necesita descender de a poco')),
                ('theparser', models.CharField(choices=[('html.parser', 'Html Parser'), ('lxml', 'Lxml'), ('html5lib', 'Htm5Lib')], default='html.parser', help_text='Este campo es utilizado en ?', max_length=20)),
                ('crawler', models.CharField(choices=[('BeautifulSoup', 'Beautifulsoup'), ('Selennium', 'Selenium')], help_text='Scan pages with', max_length=20)),
                ('url_suffix', models.CharField(blank=True, max_length=250, null=True)),
                ('page_parameter', models.CharField(blank=True, default='?page=', max_length=50, null=True)),
                ('page_suffix', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('notas', models.TextField(blank=True, default='', null=True)),
                ('sitemap_url', models.URLField(blank=True, default='', help_text='URL del sitemap', null=True)),
                ('enable', models.BooleanField(default=True)),
                ('actualizando', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='site_icons/', verbose_name='Menu Icon Image')),
                ('cobertura_url', models.URLField(blank=True, default='', help_text='URL de coberturas', max_length=600, null=True)),
                ('es_ean13', models.BooleanField(default=False, help_text='Sitio utiliza ID como EAN13')),
                ('reclamos_url', models.URLField(blank=True, default='', help_text='URL de reclamos', max_length=600, null=True)),
                ('product_url', models.URLField(blank=True, default='', help_text='URL de producto debe comenzar con', max_length=400, null=True)),
                ('use_his_image', models.BooleanField(default=True)),
                ('desp_monto_minimo', models.IntegerField(default=0, help_text='El mínimo para realizar una compra con despacho a domicilio es de')),
                ('account', models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.account')),
                ('corporacion', models.ForeignKey(default=1, help_text='Grupo de empresas', on_delete=django.db.models.deletion.SET_DEFAULT, to='precios.corporation')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='SiteURLResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('error404', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('secondsToGet', models.PositiveIntegerField(default=0)),
                ('precio', models.IntegerField(default=0)),
                ('precio_cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=650, null=True)),
                ('idproducto', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('marca', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('medida_um', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('medida_cant', models.FloatField(default=0)),
                ('categoria', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('tipo', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('proveedor', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('stock', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('precioref', models.IntegerField(default=0)),
                ('unidades', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.URLField(blank=True, default='', max_length=600, null=True)),
            ],
            options={
                'verbose_name': 'URL encontrada en sitio',
                'verbose_name_plural': 'URLs encontradas en sitio',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.articulos')),
                ('vendidoen', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.siteurlresults')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Unifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('si_grados2', models.FloatField(default=0)),
                ('si_medida_cant', models.FloatField(default=0)),
                ('si_unidades', models.IntegerField(default=1)),
                ('entonces_nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('entonces_grados2', models.FloatField(default=0)),
                ('entonces_medida_cant', models.FloatField(default=0)),
                ('entonces_unidades', models.IntegerField(default=1)),
                ('contador', models.IntegerField(default=0)),
                ('automatico', models.BooleanField(default=False)),
                ('entonces_marca', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entonces_marca', to='precios.marcas')),
                ('si_marca', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='si_marca', to='precios.marcas')),
            ],
            options={
                'verbose_name': 'Unifica',
                'ordering': ('si_marca', 'si_nombre', 'si_medida_cant', 'si_grados2', 'si_unidades'),
            },
        ),
        migrations.AddField(
            model_name='siteurlresults',
            name='reglas',
            field=models.ManyToManyField(blank=True, default=None, related_name='las_reglas', to='precios.Unifica'),
        ),
        migrations.AddField(
            model_name='siteurlresults',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.site'),
        ),
        migrations.CreateModel(
            name='SiteMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.URLField(blank=True, default='', help_text='URL del sitemap', max_length=600, null=True)),
                ('sitemap_type', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('get_url', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastmod', models.DateField()),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.site')),
            ],
            options={
                'verbose_name': 'SiteMap',
                'verbose_name_plural': 'SiteMaps',
            },
        ),
        migrations.CreateModel(
            name='SelectorCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(choices=[('xpath', 'Xpath'), ('css selector', 'Css Selector'), ('meta', 'Meta'), ('ninguno', 'Ninguno'), ('valorfijo', 'Valorfijo')], default='xpath', help_text='como selecciona ?', max_length=20)),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('meta_opcion', models.CharField(choices=[('None', 'None'), ('charset', 'Charset'), ('name', 'Name'), ('property', 'Property')], default='None', help_text='Meta que ?', max_length=20)),
                ('que_busca', models.CharField(blank=True, help_text='c-block.c-product.js-product-single o product:retailer_item_id. Si es FIJO, introduzca valor a guardar', max_length=650)),
                ('printit', models.BooleanField(default=False)),
                ('removeChars', models.CharField(blank=True, max_length=650, null=True)),
                ('que_obtiene', models.CharField(blank=True, default='text', max_length=650, null=True)),
                ('split_return_by', models.CharField(blank=True, max_length=6, null=True)),
                ('split_get_element', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_description', models.CharField(blank=True, max_length=650, null=True)),
                ('campo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='precios.camposensitio')),
            ],
            options={
                'verbose_name': 'Selector de campo',
                'verbose_name_plural': 'Selectores de campo',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('code', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.countries')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oldprecio', models.IntegerField(default=0)),
                ('OldDate', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('FromResult', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.siteurlresults')),
            ],
            options={
                'verbose_name': 'Precio historico',
                'verbose_name_plural': 'Precios historicos',
                'ordering': ('-OldDate',),
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=250)),
                ('enabled', models.BooleanField(default=True)),
                ('got_404', models.BooleanField(default=False)),
                ('lastPageIndexed', models.IntegerField(default=0)),
                ('maxPagesFound', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_scan', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.site')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='MomentosDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaDespacho', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.areasdespacho')),
                ('dia', models.ManyToManyField(to='precios.DiasSemana')),
                ('horario', models.ManyToManyField(to='precios.HorasDespacho')),
            ],
            options={
                'verbose_name': 'Momento del despacho',
                'verbose_name_plural': 'Momentos de despacho',
            },
        ),
        migrations.CreateModel(
            name='FixTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_busca', precios.models.LowerField(help_text='artesanos de cochiguaz', max_length=100)),
                ('reemplazacon', precios.models.LowerField(blank=True, default='', help_text='Artesanos del Cochiguaz', max_length=100)),
                ('campo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.camposensitio')),
            ],
            options={
                'verbose_name': 'FixTerm',
                'verbose_name_plural': 'FixTerms',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('cut', models.IntegerField(default=0, help_text='Código Único Territorial', null=True)),
                ('superficie', models.IntegerField(default=0, help_text='Superficie (km²)', null=True)),
                ('poblacion', models.IntegerField(default=0, help_text='Población 2020', null=True)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.countries')),
                ('region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.regions')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ('region', 'name'),
            },
        ),
        migrations.AddField(
            model_name='camposensitio',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.site'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.marcas'),
        ),
        migrations.AddField(
            model_name='areasdespacho',
            name='comuna',
            field=models.ManyToManyField(to='precios.Cities'),
        ),
        migrations.AddField(
            model_name='areasdespacho',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.site'),
        ),
        migrations.AddIndex(
            model_name='vendedores',
            index=models.Index(fields=['articulo'], name='precios_ven_articul_03f445_idx'),
        ),
        migrations.AddIndex(
            model_name='vendedores',
            index=models.Index(fields=['vendidoen'], name='precios_ven_vendido_89e80c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendedores',
            unique_together={('articulo', 'vendidoen')},
        ),
        migrations.AlterIndexTogether(
            name='vendedores',
            index_together={('articulo', 'vendidoen')},
        ),
        migrations.AlterUniqueTogether(
            name='unifica',
            unique_together={('si_marca', 'si_nombre', 'si_medida_cant', 'si_grados2', 'si_unidades')},
        ),
        migrations.AlterIndexTogether(
            name='unifica',
            index_together={('si_marca', 'si_nombre', 'si_medida_cant', 'si_grados2', 'si_unidades')},
        ),
        migrations.AlterIndexTogether(
            name='siteurlresults',
            index_together={('site', 'url')},
        ),
        migrations.AlterUniqueTogether(
            name='sitemap',
            unique_together={('site', 'loc')},
        ),
        migrations.AlterIndexTogether(
            name='sitemap',
            index_together={('site', 'loc')},
        ),
        migrations.AlterUniqueTogether(
            name='selectorcampo',
            unique_together={('campo', 'selector', 'my_order')},
        ),
        migrations.AlterIndexTogether(
            name='selectorcampo',
            index_together={('campo', 'my_order')},
        ),
        migrations.AlterUniqueTogether(
            name='regions',
            unique_together={('country', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='pricehistory',
            index_together={('FromResult',)},
        ),
        migrations.AlterUniqueTogether(
            name='pages',
            unique_together={('site', 'page')},
        ),
        migrations.AlterIndexTogether(
            name='pages',
            index_together={('site', 'page')},
        ),
        migrations.AlterUniqueTogether(
            name='fixterm',
            unique_together={('campo', 'que_busca')},
        ),
        migrations.AlterIndexTogether(
            name='fixterm',
            index_together={('campo', 'que_busca')},
        ),
        migrations.AlterUniqueTogether(
            name='cities',
            unique_together={('country', 'region', 'name')},
        ),
        migrations.AddIndex(
            model_name='articulos',
            index=models.Index(fields=['marca', 'nombre', 'medida_cant', 'unidades'], name='articulo_id1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articulos',
            unique_together={('marca', 'nombre', 'medida_cant', 'grados', 'unidades')},
        ),
        migrations.AlterIndexTogether(
            name='articulos',
            index_together={('marca', 'nombre', 'medida_cant', 'grados', 'unidades')},
        ),
    ]
