# Generated by Django 3.2.18 on 2023-05-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0004_allpalabras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allpalabras',
            options={'ordering': ('palabra',), 'verbose_name': 'AllPalabras', 'verbose_name_plural': 'AllPalabras'},
        ),
    ]
