# Generated by Django 3.2.18 on 2023-05-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0006_allpalabras_contador'),
    ]

    operations = [
        migrations.AddField(
            model_name='reemplazapalabras',
            name='contador',
            field=models.IntegerField(default=0),
        ),
    ]
