# Generated by Django 3.2.18 on 2023-06-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0008_unifica_tipo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articulos',
            name='articulo_id1_idx',
        ),
        migrations.AddIndex(
            model_name='articulos',
            index=models.Index(fields=['marca', 'nombre', 'medida_cant', 'grados2', 'unidades'], name='articulo_id1_idx'),
        ),
    ]
