# Generated by Django 3.2.18 on 2023-06-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0012_alter_articulos_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'ordering': ('marca', 'nombre', 'medida_cant', 'grados2', 'unidades'), 'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
        migrations.AlterUniqueTogether(
            name='articulos',
            unique_together={('marca', 'nombre', 'medida_cant', 'grados2', 'unidades')},
        ),
    ]
