# Generated by Django 3.2.18 on 2023-06-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0018_alter_articulos_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articulos',
            name='articulo_id1_idx',
        ),
        migrations.AlterField(
            model_name='reemplazapalabras',
            name='reemplazo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
