# Generated by Django 3.2.18 on 2023-06-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0019_auto_20230609_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpalabras',
            name='tipo',
            field=models.CharField(choices=[('Inútiles', 'Inutil'), ('Unidades de medida', 'Umedida'), ('Sufijos de nombre', 'Sujifo Nombre'), ('Unidades', 'Unidad'), ('Packs', 'Packs'), ('Tallas', 'Talla'), ('Colores', 'Color'), ('Envases', 'Envase')], default='', help_text='Palabra es tipo', max_length=20),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='articulos',
            index=models.Index(fields=['marca', 'nombre', 'medida_cant', 'grados2', 'unidades', 'envase'], name='articulo_id1_idx'),
        ),
    ]
