# Generated by Django 3.2.18 on 2023-06-10 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0022_auto_20230610_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unifica',
            options={'ordering': ('si_marca', 'si_nombre', 'si_medida_cant', 'si_grados2', 'si_unidades', 'si_envase'), 'verbose_name': 'Unifica'},
        ),
#        migrations.AlterUniqueTogether(
#            name='unifica',
#            unique_together={('si_marca', 'si_nombre', 'si_medida_cant', 'si_grados2', 'si_unidades', 'si_envase')},
#        ),
#        migrations.AlterIndexTogether(
#            name='unifica',
#            index_together={('si_marca', 'si_nombre', 'si_medida_cant', 'si_grados2', 'si_unidades', 'si_envase')},
#        ),
    ]
