# Generated by Django 3.2.18 on 2023-06-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0023_auto_20230610_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unifica',
            options={'verbose_name': 'Unifica'},
        ),
#        migrations.AlterUniqueTogether(
#            name='unifica',
#            unique_together=set(),
#        ),
#        migrations.AlterIndexTogether(
#            name='unifica',
#            index_together=set(),
#        ),
        migrations.AddConstraint(
            model_name='unifica',
            constraint=models.UniqueConstraint(fields=('si_marca', 'si_nombre', 'si_medida_cant', 'si_grados2', 'si_unidades', 'si_envase'), name='unique_if_not_deleted'),
        ),
    ]
