# Generated by Django 3.2.18 on 2023-07-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0024_auto_20230618_1826'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unifica',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='unifica',
            index_together=set(),
        ),
    ]
