# Generated by Django 3.2.18 on 2023-07-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0025_auto_20230724_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='product_category',
            field=models.CharField(blank=True, help_text='Parte de URL que identifica categoria', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='product_palabras_evitar',
            field=models.CharField(blank=True, help_text='Parte de URL para no escanear como map= _q= separar por coma', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='product_product',
            field=models.CharField(blank=True, help_text='Parte de URL que identifica un producto', max_length=250, null=True),
        ),
    ]
