# Generated by Django 3.2.18 on 2023-08-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0027_auto_20230808_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, help_text='Dirección', max_length=300, null=True)),
                ('comuna', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.cities')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.AlterField(
            model_name='site',
            name='crawler',
            field=models.CharField(choices=[('BeautifulSoup', 'Beautifulsoup'), ('Selennium', 'Selenium'), ('Ninguno', 'Ninguno')], help_text='Scan pages with', max_length=20),
        ),
        migrations.CreateModel(
            name='Horario_atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ManyToManyField(to='precios.DiasSemana')),
                ('direccion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.direccion')),
                ('horario', models.ManyToManyField(to='precios.HorasDespacho')),
            ],
            options={
                'verbose_name': 'Horario atencion',
                'verbose_name_plural': 'Horarios de atencion',
            },
        ),
        migrations.AddField(
            model_name='direccion',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='precios.site'),
        ),
    ]
