# Generated by Django 3.2.18 on 2023-08-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0030_alter_siteurlresults_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteurlresults',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
