# Generated by Django 3.2.18 on 2023-09-05 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0031_alter_siteurlresults_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
    ]
