# Generated by Django 3.2.18 on 2023-09-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0032_auto_20230905_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cities',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
