# Generated by Django 3.2.18 on 2023-09-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0033_auto_20230917_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='talla',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
