# Generated by Django 3.2.18 on 2023-09-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0034_articulos_talla'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articulos',
            name='articulo_id1_idx',
        ),
        migrations.AddIndex(
            model_name='articulos',
            index=models.Index(fields=['marca', 'nombre', 'medida_cant', 'grados2', 'unidades', 'envase', 'talla'], name='articulo_id1_idx'),
        ),
    ]
