# Generated by Django 3.2.18 on 2023-09-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0035_auto_20230928_1607'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='articulos',
            index_together={('marca', 'nombre', 'medida_cant', 'grados2', 'unidades', 'envase', 'talla')},
        ),
    ]
