# Generated by Django 3.2.18 on 2023-09-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0040_auto_20230928_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allpalabras',
            unique_together={('tipo', 'palabra')},
        ),
    ]
