# Generated by Django 3.2.18 on 2023-09-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0041_alter_allpalabras_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpalabras',
            name='palabra',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
