# Generated by Django 3.2.18 on 2023-05-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
    ]
