# Generated by Django 3.2.18 on 2023-05-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0003_reemplazapalabras'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPalabras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
    ]
