# Generated by Django 3.2.18 on 2023-05-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0005_alter_allpalabras_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpalabras',
            name='contador',
            field=models.IntegerField(default=0),
        ),
    ]
