# Generated by Django 3.2.18 on 2023-06-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0007_reemplazapalabras_contador'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifica',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
