# Generated by Django 3.2.18 on 2023-06-01 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0009_auto_20230601_1758'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='articulos',
            index_together={('marca', 'nombre', 'medida_cant', 'grados2', 'unidades')},
        ),
    ]
