# Generated by Django 3.2.18 on 2023-06-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0010_alter_articulos_index_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articulos',
            unique_together=set(),
        ),
    ]
