# Generated by Django 3.2.18 on 2023-06-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0011_alter_articulos_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articulos',
            unique_together={('marca', 'nombre', 'medida_cant', 'grados', 'unidades')},
        ),
    ]
