# Generated by Django 3.2.18 on 2023-06-08 15:49

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0013_auto_20230602_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['marca__slug', 'nombre', 'medida_cant', 'unidades', 'envase', 'grados2'], unique=True),
        ),
    ]
