# Generated by Django 3.2.18 on 2023-06-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0019_alter_reemplazapalabras_reemplazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reemplazapalabras',
            name='reemplazo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
