# Generated by Django 3.2.18 on 2023-06-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0020_alter_reemplazapalabras_reemplazo'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='allpalabras',
#            name='tipo',
#            field=models.CharField(blank=True, choices=[('Inútiles', 'Inutil'), ('Unidades de medida', 'Umedida'), ('Sufijos de nombre', 'Sujifo Nombre'), ('Unidades', 'Unidad'), ('Packs', 'Packs'), ('Tallas', 'Talla'), ('Colores', 'Color'), ('Envases', 'Envase')], help_text='Palabra es tipo', max_length=20, null=True),
#        ),
        migrations.AddField(
            model_name='unifica',
            name='entonces_envase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unifica',
            name='si_envase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
