# Generated by Django 3.2.18 on 2023-06-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0021_auto_20230610_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unifica',
            options={'verbose_name': 'Unifica'},
        ),
#        migrations.AddField(
#            model_name='allpalabras',
#            name='tipo',
#            field=models.CharField(blank=True, choices=[('Inútiles', 'Inutil'), ('Unidades de medida', 'Umedida'), ('Sufijos de nombre', 'Sujifo Nombre'), ('Unidades', 'Unidad'), ('Packs', 'Packs'), ('Tallas', 'Talla'), ('Colores', 'Color'), ('Envases', 'Envase')], help_text='Palabra es tipo', max_length=20, null=True),
#        ),
        migrations.AlterUniqueTogether(
            name='unifica',
            unique_together={('si_marca', 'si_nombre', 'si_medida_cant','si_grados2','si_unidades')},
        ),
        migrations.AlterIndexTogether(
            name='unifica',
            index_together={('si_marca', 'si_nombre', 'si_medida_cant','si_grados2','si_unidades')},
        ),
    ]
