# Generated by Django 3.2.18 on 2023-06-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0023_auto_20230612_1738'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unifica',
            constraint=models.UniqueConstraint(fields=('si_marca', 'si_nombre', 'si_medida_cant', 'si_grados2', 'si_unidades', 'si_envase'), name='unique_if_not_deleted'),
        ),
    ]
