# Generated by Django 3.2.18 on 2023-08-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0026_auto_20230724_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica_Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_consultada', models.CharField(max_length=100)),
                ('elemento_id', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('cantidad_vista', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estadistica Consultas',
                'verbose_name_plural': 'Estadisticas de Consultas',
                'ordering': ('clase_consultada', 'fecha'),
            },
        ),
        migrations.AddIndex(
            model_name='estadistica_consulta',
            index=models.Index(fields=['clase_consultada', 'elemento_id'], name='precios_est_clase_c_af2cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='estadistica_consulta',
            index=models.Index(fields=['fecha'], name='precios_est_fecha_b05646_idx'),
        ),
    ]
