# Generated by Django 3.2.18 on 2023-08-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0027_auto_20230808_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Estadisticas Black List',
                'verbose_name_plural': 'Estadisticas Black List',
            },
        ),
    ]
