# Generated by Django 3.2.18 on 2023-08-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0028_estadisticasblacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticasblacklist',
            name='no_contabilizar',
            field=models.BooleanField(default=False),
        ),
    ]
