# Generated by Django 3.2.18 on 2023-08-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0029_estadisticasblacklist_no_contabilizar'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadistica_consulta',
            name='texto_busqueda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
