# Generated by Django 3.2.18 on 2023-08-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0030_estadistica_consulta_texto_busqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasdespacho',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='areasdespacho',
            name='es_despacho',
            field=models.BooleanField(default=False, help_text='Es despacho'),
        ),
    ]
