# Generated by Django 3.2.18 on 2023-08-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0031_auto_20230809_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areasdespacho',
            name='es_despacho',
        ),
        migrations.AddField(
            model_name='areasdespacho',
            name='no_es_despacho',
            field=models.BooleanField(default=False, help_text='No es despacho'),
        ),
    ]
