# Generated by Django 3.2.18 on 2023-08-09 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0034_direccion_horario_atencion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
    ]
