# Generated by Django 3.2.18 on 2023-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0035_alter_direccion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='crawler',
            field=models.CharField(choices=[('BeautifulSoup', 'Beautifulsoup'), ('Selennium', 'Selenium'), ('Ninguno', 'Ninguno')], help_text='Scan pages with', max_length=20),
        ),
    ]
