# Generated by Django 3.2.18 on 2023-08-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0037_alter_site_corporacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemap',
            name='lastmod',
            field=models.DateField(auto_now=True),
        ),
    ]
