# Generated by Django 3.2.18 on 2023-05-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
#        ('precios', '0013_remove_unifica_entonces_grados'),
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.ForeignKey(blank=True, help_text='País', null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.countries'),
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Región', null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.regions'),
        ),
        migrations.AlterField(
            model_name='member',
            name='comuna',
            field=models.ForeignKey(blank=True, help_text='Comuna', null=True, on_delete=django.db.models.deletion.PROTECT, to='precios.cities'),
        ),
        migrations.AlterField(
            model_name='member',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección', max_length=250, null=True),
        ),
    ]
