# Generated by Django 3.2.18 on 2023-08-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0028_auto_20230814_1714'),
        ('members', '0004_auto_20230815_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='account2',
            field=models.ForeignKey(blank=True, default=4, help_text='Cuenta', null=True, on_delete=django.db.models.deletion.PROTECT, to='members.account'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='icono',
            field=models.CharField(blank=True, help_text='Icono del plan', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now=True, help_text='Fecha de inicio del contrato')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización del contrato', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(help_text='Miembros asociados al contrato', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='members.member')),
                ('plan', models.ForeignKey(help_text='Planes asociados al contrato', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='members.plan')),
                ('site', models.ForeignKey(help_text='Sitios asociados al contrato', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='precios.site')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
