# Generated by Django 3.2.18 on 2023-05-24 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='ContenidoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(choices=[('Usuarios.', 'Usuarios'), ('Listas de productos almacenados.', 'Listas'), ('Búsquedas.', 'Busquedas'), ('Búsquedas en marcas.', 'Busq Marcas'), ('Emails de lista.', 'Emails'), ('Comunas de despacho de un país.', 'Comunas'), ('Supermercados o Proveedores que despachan en su(s) comuna(s) en un país.', 'Super Proveed'), ('Productos en lista.', 'Prod En Lista'), ('Informes.', 'Informes'), ('Productos.', 'Productos'), ('Cuentas Básico.', 'Cuentas Basico'), ('Cuentas Avanzado.', 'Cuentas Avanzado'), ('Cuentas Empresa.', 'Cuentas Empresa')], default='Usuarios.', help_text='Nombre del Objeto, usuario, comunas, supermercados, listas, productos por lista, busquedas, emails', max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Cantidad Maxima al mes')),
                ('todos', models.BooleanField(default=False)),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contenido en Plan',
                'verbose_name_plural': 'Contenido en Planes',
                'ordering': ('plan', 'objeto', 'my_order'),
            },
        ),
        migrations.CreateModel(
            name='DetalleLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Detalles de Lista',
                'verbose_name_plural': 'Detalles de Listas',
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lista', models.CharField(blank=True, help_text='Nombre de su lista', max_length=250, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'ordering': ('member', 'nombre_lista'),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, help_text='Dirección', max_length=250, null=True)),
                ('account2', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.account')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('last_update', models.DateField(auto_now=True)),
                ('closed', models.BooleanField(default=False, verbose_name='Data on this period is gotten')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del plan', max_length=250, null=True)),
                ('leyenda', models.CharField(blank=True, help_text='Leyenda del plan', max_length=400, null=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del plan', max_length=100, null=True)),
                ('area_class', models.CharField(blank=True, help_text='Bootstrap  class', max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('Personas', 'Personas'), ('Ofrecen', 'Ofrecen')], default='Personas', help_text='Tipo de plan', max_length=30)),
                ('clase', models.CharField(choices=[('Básico', 'Basico'), ('Avanzado', 'Avanzado'), ('Empresa', 'Empresa'), ('Empresa Free', 'Empresa Free')], default='Básico', help_text='Clase de plan ', max_length=30)),
                ('valor_mes', models.PositiveIntegerField(default=0)),
                ('valor_agno', models.PositiveIntegerField(default=0)),
                ('descto_anual', models.PositiveIntegerField(default=0, help_text='Porcentaje de descuento')),
                ('leyenda_valor', models.CharField(blank=True, help_text='Algo como Siempre, por este mes, etc', max_length=40, null=True)),
                ('boton_registrarse_texto', models.CharField(blank=True, help_text='Registrese o No activo', max_length=100, null=True)),
                ('boton_registrarse_url', models.CharField(blank=True, help_text='URL para registrarse,  # si es ninguna', max_length=200, null=True)),
                ('costo_implementacion', models.PositiveIntegerField(default=0, help_text='Costo mínimo de implementación')),
                ('notas_internas', models.TextField(blank=True, default='', null=True)),
                ('notas_web', models.TextField(blank=True, default='', null=True)),
                ('publico', models.BooleanField(default=True, help_text='Plan visible en Internet')),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ('tipo', 'clase', 'valor_mes'),
                'unique_together': {('tipo', 'clase')},
            },
        ),
        migrations.CreateModel(
            name='MemberStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(choices=[('Usuarios.', 'Usuarios'), ('Listas de productos almacenados.', 'Listas'), ('Búsquedas.', 'Busquedas'), ('Búsquedas en marcas.', 'Busq Marcas'), ('Emails de lista.', 'Emails'), ('Comunas de despacho de un país.', 'Comunas'), ('Supermercados o Proveedores que despachan en su(s) comuna(s) en un país.', 'Super Proveed'), ('Productos en lista.', 'Prod En Lista'), ('Informes.', 'Informes'), ('Productos.', 'Productos'), ('Cuentas Básico.', 'Cuentas Basico'), ('Cuentas Avanzado.', 'Cuentas Avanzado'), ('Cuentas Empresa.', 'Cuentas Empresa')], default='Usuarios.', help_text='Nombre del Objeto, usuario, comunas, supermercados, listas, productos por lista, busquedas, emails', max_length=100)),
                ('cuantity', models.BigIntegerField(null=True)),
                ('member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.periodo')),
            ],
            options={
                'verbose_name': 'MemberStats',
                'verbose_name_plural': 'MemberStats',
                'ordering': ['member', 'objeto', '-period'],
            },
        ),
    ]
