# Generated by Django 3.2.18 on 2023-05-24 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('precios', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='comuna',
            field=models.ForeignKey(blank=True, help_text='Comuna', null=True, on_delete=django.db.models.deletion.PROTECT, to='precios.cities'),
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.ForeignKey(blank=True, help_text='País', null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.countries'),
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Región', null=True, on_delete=django.db.models.deletion.SET_NULL, to='precios.regions'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lista',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
        migrations.AddField(
            model_name='detallelista',
            name='articulo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='precios.articulos'),
        ),
        migrations.AddField(
            model_name='detallelista',
            name='lista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.lista'),
        ),
        migrations.AddField(
            model_name='contenidoplan',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.plan'),
        ),
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.plan'),
        ),
        migrations.AlterUniqueTogether(
            name='memberstats',
            unique_together={('member', 'objeto', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='lista',
            unique_together={('member', 'nombre_lista')},
        ),
        migrations.AlterUniqueTogether(
            name='contenidoplan',
            unique_together={('plan', 'objeto')},
        ),
    ]
