# Generated by Django 3.2.18 on 2023-08-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20230524_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidoplan',
            name='objeto',
            field=models.CharField(choices=[('Usuarios.', 'Usuarios'), ('Listas de productos almacenados.', 'Listas'), ('Búsquedas.', 'Busquedas'), ('Búsquedas en marcas.', 'Busq Marcas'), ('Emails de lista.', 'Emails'), ('Comunas de despacho o ubicacion de un país.', 'Comunas'), ('Supermercados o Proveedores que despachan en su(s) comuna(s) en un país.', 'Super Proveed'), ('Productos en lista.', 'Prod En Lista'), ('Informes.', 'Informes'), ('Productos.', 'Productos'), ('Cuentas Básico.', 'Cuentas Basico'), ('Cuentas Avanzado.', 'Cuentas Avanzado'), ('Cuentas Empresa.', 'Cuentas Empresa')], default='Usuarios.', help_text='Nombre del Objeto, usuario, comunas, supermercados, listas, productos por lista, busquedas, emails', max_length=100),
        ),
        migrations.AlterField(
            model_name='memberstats',
            name='objeto',
            field=models.CharField(choices=[('Usuarios.', 'Usuarios'), ('Listas de productos almacenados.', 'Listas'), ('Búsquedas.', 'Busquedas'), ('Búsquedas en marcas.', 'Busq Marcas'), ('Emails de lista.', 'Emails'), ('Comunas de despacho o ubicacion de un país.', 'Comunas'), ('Supermercados o Proveedores que despachan en su(s) comuna(s) en un país.', 'Super Proveed'), ('Productos en lista.', 'Prod En Lista'), ('Informes.', 'Informes'), ('Productos.', 'Productos'), ('Cuentas Básico.', 'Cuentas Basico'), ('Cuentas Avanzado.', 'Cuentas Avanzado'), ('Cuentas Empresa.', 'Cuentas Empresa')], default='Usuarios.', help_text='Nombre del Objeto, usuario, comunas, supermercados, listas, productos por lista, busquedas, emails', max_length=100),
        ),
    ]
