# Generated by Django 3.2.18 on 2023-08-17 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20230809_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxClassifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='Name')),
                ('taxable', models.BooleanField(verbose_name='Taxable')),
            ],
            options={
                'verbose_name': 'Product Classifier',
                'verbose_name_plural': 'Product Classifiers',
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='account2',
            field=models.ForeignKey(blank=True, default=4, help_text='Cuenta', null=True, on_delete=django.db.models.deletion.PROTECT, to='members.account'),
        ),
    ]
