# Generated by Django 3.2.18 on 2023-08-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_plan_icono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxClassifier',
        ),
    ]
