# Generated by Django 3.2.18 on 2023-08-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0037_alter_site_corporacion'),
        ('members', '0007_delete_taxclassifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now=True, help_text='Fecha de inicio del contrato')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización del contrato', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(help_text='Miembros asociados al contrato', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='members.member')),
                ('plan', models.ForeignKey(help_text='Planes asociados al contrato', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='members.plan')),
                ('site', models.ForeignKey(help_text='Sitios asociados al contrato', on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='precios.site')),
            ],
        ),
    ]
