# Generated by Django 3.2.18 on 2023-08-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
    ]
